plot(1:100,1:100,type="n")
curve(x^2/100,add=TRUE)
text(80,50,"this is a graph of")
points(x=rep(100,10),y=seq(0,90,10),pch=seq(1,20,2))
abline(a=-18,b=1.1,col="red")
abline(h=20,lty=2)
## we'll try and make different types of ploti
install.packages("iplots")
library(iplots)
library(ggplot2)
library(tabplot)
install.packages("tabplot")
library(rattle)
library(dplyr)

##using the dialplot for R
source("http://onepager.togaware.com/dial.plot.R")
dial.plot(label = "OnePagerR",value = 65,value.color = "blue")
par(mfrow=c(2,3))
dial.plot(label="Temperature",value=85,value.cex=2)
dial.plot(label="Humidity",value=85,value.cex=2)
dial.plot(label="Sunshine",value=65,value.cex=2)
dial.plot(label="Rainful",value=45,value.cex=2)
dial.plot(label="Electricity",value=35,value.cex=2)
dial.plot(label="Electricity\n consumed",value=45,value.cex=2)
par(mfrow=c(1,1))
library(tabplot)
tableplot(weather,select=c(MinTemp:WindDir3pm,RainTomorrow))
